// **********************************************************************
//
// Copyright (c) 2003-2013 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.5.1
//
// <auto-generated>
//
// Generated from file `Stream.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package streaming;

public interface TrackPrx extends Ice.ObjectPrx
{
    public void viewAllTract();

    public void viewAllTract(java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_viewAllTract();

    public Ice.AsyncResult begin_viewAllTract(java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_viewAllTract(Ice.Callback __cb);

    public Ice.AsyncResult begin_viewAllTract(java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_viewAllTract(Callback_Track_viewAllTract __cb);

    public Ice.AsyncResult begin_viewAllTract(java.util.Map<String, String> __ctx, Callback_Track_viewAllTract __cb);

    public void end_viewAllTract(Ice.AsyncResult __result);
}
