// **********************************************************************
//
// Copyright (c) 2003-2013 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.5.1
//
// <auto-generated>
//
// Generated from file `Stream.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

#ifndef __Stream_h__
#define __Stream_h__

#include <Ice/ProxyF.h>
#include <Ice/ObjectF.h>
#include <Ice/Exception.h>
#include <Ice/LocalObject.h>
#include <Ice/StreamHelpers.h>
#include <Ice/Proxy.h>
#include <Ice/Object.h>
#include <Ice/Outgoing.h>
#include <Ice/OutgoingAsync.h>
#include <Ice/Incoming.h>
#include <Ice/Direct.h>
#include <IceUtil/ScopedArray.h>
#include <IceUtil/Optional.h>
#include <Ice/StreamF.h>
#include <Ice/UndefSysMacros.h>

#ifndef ICE_IGNORE_VERSION
#   if ICE_INT_VERSION / 100 != 305
#       error Ice version mismatch!
#   endif
#   if ICE_INT_VERSION % 100 > 50
#       error Beta header file detected
#   endif
#   if ICE_INT_VERSION % 100 < 1
#       error Ice patch level mismatch!
#   endif
#endif

namespace IceProxy
{

namespace streaming
{

class Track;
void __read(::IceInternal::BasicStream*, ::IceInternal::ProxyHandle< ::IceProxy::streaming::Track>&);
::IceProxy::Ice::Object* upCast(::IceProxy::streaming::Track*);

class Player;
void __read(::IceInternal::BasicStream*, ::IceInternal::ProxyHandle< ::IceProxy::streaming::Player>&);
::IceProxy::Ice::Object* upCast(::IceProxy::streaming::Player*);

}

}

namespace streaming
{

class Track;
bool operator==(const Track&, const Track&);
bool operator<(const Track&, const Track&);
::Ice::Object* upCast(::streaming::Track*);
typedef ::IceInternal::Handle< ::streaming::Track> TrackPtr;
typedef ::IceInternal::ProxyHandle< ::IceProxy::streaming::Track> TrackPrx;
void __patch(TrackPtr&, const ::Ice::ObjectPtr&);

class Player;
bool operator==(const Player&, const Player&);
bool operator<(const Player&, const Player&);
::Ice::Object* upCast(::streaming::Player*);
typedef ::IceInternal::Handle< ::streaming::Player> PlayerPtr;
typedef ::IceInternal::ProxyHandle< ::IceProxy::streaming::Player> PlayerPrx;
void __patch(PlayerPtr&, const ::Ice::ObjectPtr&);

}

namespace streaming
{

class Callback_Track_viewAllTract_Base : virtual public ::IceInternal::CallbackBase { };
typedef ::IceUtil::Handle< Callback_Track_viewAllTract_Base> Callback_Track_viewAllTractPtr;

class Callback_Player_addTrack_Base : virtual public ::IceInternal::CallbackBase { };
typedef ::IceUtil::Handle< Callback_Player_addTrack_Base> Callback_Player_addTrackPtr;

class Callback_Player_deleteTrack_Base : virtual public ::IceInternal::CallbackBase { };
typedef ::IceUtil::Handle< Callback_Player_deleteTrack_Base> Callback_Player_deleteTrackPtr;

class Callback_Player_searchTrack_Base : virtual public ::IceInternal::CallbackBase { };
typedef ::IceUtil::Handle< Callback_Player_searchTrack_Base> Callback_Player_searchTrackPtr;

class Callback_Player_playTrack_Base : virtual public ::IceInternal::CallbackBase { };
typedef ::IceUtil::Handle< Callback_Player_playTrack_Base> Callback_Player_playTrackPtr;

}

namespace IceProxy
{

namespace streaming
{

class Track : virtual public ::IceProxy::Ice::Object
{
public:

    void viewAllTract()
    {
        viewAllTract(0);
    }
    void viewAllTract(const ::Ice::Context& __ctx)
    {
        viewAllTract(&__ctx);
    }
#ifdef ICE_CPP11
    ::Ice::AsyncResultPtr
    begin_viewAllTract(const ::IceInternal::Function<void ()>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& __sent = ::IceInternal::Function<void (bool)>())
    {
        return begin_viewAllTract(0, new ::IceInternal::Cpp11FnOnewayCallbackNC(__response, __exception, __sent));
    }
    ::Ice::AsyncResultPtr
    begin_viewAllTract(const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_viewAllTract(0, ::Ice::newCallback(__completed, __sent), 0);
    }
    ::Ice::AsyncResultPtr
    begin_viewAllTract(const ::Ice::Context& __ctx, const ::IceInternal::Function<void ()>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& __sent = ::IceInternal::Function<void (bool)>())
    {
        return begin_viewAllTract(&__ctx, new ::IceInternal::Cpp11FnOnewayCallbackNC(__response, __exception, __sent), 0);
    }
    ::Ice::AsyncResultPtr
    begin_viewAllTract(const ::Ice::Context& __ctx, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_viewAllTract(&__ctx, ::Ice::newCallback(__completed, __sent));
    }
#endif

    ::Ice::AsyncResultPtr begin_viewAllTract()
    {
        return begin_viewAllTract(0, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_viewAllTract(const ::Ice::Context& __ctx)
    {
        return begin_viewAllTract(&__ctx, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_viewAllTract(const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_viewAllTract(0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_viewAllTract(const ::Ice::Context& __ctx, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_viewAllTract(&__ctx, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_viewAllTract(const ::streaming::Callback_Track_viewAllTractPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_viewAllTract(0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_viewAllTract(const ::Ice::Context& __ctx, const ::streaming::Callback_Track_viewAllTractPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_viewAllTract(&__ctx, __del, __cookie);
    }

    void end_viewAllTract(const ::Ice::AsyncResultPtr&);
    
private:

    void viewAllTract(const ::Ice::Context*);
    ::Ice::AsyncResultPtr begin_viewAllTract(const ::Ice::Context*, const ::IceInternal::CallbackBasePtr&, const ::Ice::LocalObjectPtr& __cookie = 0);
    
public:
    
    ::IceInternal::ProxyHandle<Track> ice_context(const ::Ice::Context& __context) const
    {
        return dynamic_cast<Track*>(::IceProxy::Ice::Object::ice_context(__context).get());
    }
    
    ::IceInternal::ProxyHandle<Track> ice_adapterId(const ::std::string& __id) const
    {
        return dynamic_cast<Track*>(::IceProxy::Ice::Object::ice_adapterId(__id).get());
    }
    
    ::IceInternal::ProxyHandle<Track> ice_endpoints(const ::Ice::EndpointSeq& __endpoints) const
    {
        return dynamic_cast<Track*>(::IceProxy::Ice::Object::ice_endpoints(__endpoints).get());
    }
    
    ::IceInternal::ProxyHandle<Track> ice_locatorCacheTimeout(int __timeout) const
    {
        return dynamic_cast<Track*>(::IceProxy::Ice::Object::ice_locatorCacheTimeout(__timeout).get());
    }
    
    ::IceInternal::ProxyHandle<Track> ice_connectionCached(bool __cached) const
    {
        return dynamic_cast<Track*>(::IceProxy::Ice::Object::ice_connectionCached(__cached).get());
    }
    
    ::IceInternal::ProxyHandle<Track> ice_endpointSelection(::Ice::EndpointSelectionType __est) const
    {
        return dynamic_cast<Track*>(::IceProxy::Ice::Object::ice_endpointSelection(__est).get());
    }
    
    ::IceInternal::ProxyHandle<Track> ice_secure(bool __secure) const
    {
        return dynamic_cast<Track*>(::IceProxy::Ice::Object::ice_secure(__secure).get());
    }
    
    ::IceInternal::ProxyHandle<Track> ice_preferSecure(bool __preferSecure) const
    {
        return dynamic_cast<Track*>(::IceProxy::Ice::Object::ice_preferSecure(__preferSecure).get());
    }
    
    ::IceInternal::ProxyHandle<Track> ice_router(const ::Ice::RouterPrx& __router) const
    {
        return dynamic_cast<Track*>(::IceProxy::Ice::Object::ice_router(__router).get());
    }
    
    ::IceInternal::ProxyHandle<Track> ice_locator(const ::Ice::LocatorPrx& __locator) const
    {
        return dynamic_cast<Track*>(::IceProxy::Ice::Object::ice_locator(__locator).get());
    }
    
    ::IceInternal::ProxyHandle<Track> ice_collocationOptimized(bool __co) const
    {
        return dynamic_cast<Track*>(::IceProxy::Ice::Object::ice_collocationOptimized(__co).get());
    }
    
    ::IceInternal::ProxyHandle<Track> ice_twoway() const
    {
        return dynamic_cast<Track*>(::IceProxy::Ice::Object::ice_twoway().get());
    }
    
    ::IceInternal::ProxyHandle<Track> ice_oneway() const
    {
        return dynamic_cast<Track*>(::IceProxy::Ice::Object::ice_oneway().get());
    }
    
    ::IceInternal::ProxyHandle<Track> ice_batchOneway() const
    {
        return dynamic_cast<Track*>(::IceProxy::Ice::Object::ice_batchOneway().get());
    }
    
    ::IceInternal::ProxyHandle<Track> ice_datagram() const
    {
        return dynamic_cast<Track*>(::IceProxy::Ice::Object::ice_datagram().get());
    }
    
    ::IceInternal::ProxyHandle<Track> ice_batchDatagram() const
    {
        return dynamic_cast<Track*>(::IceProxy::Ice::Object::ice_batchDatagram().get());
    }
    
    ::IceInternal::ProxyHandle<Track> ice_compress(bool __compress) const
    {
        return dynamic_cast<Track*>(::IceProxy::Ice::Object::ice_compress(__compress).get());
    }
    
    ::IceInternal::ProxyHandle<Track> ice_timeout(int __timeout) const
    {
        return dynamic_cast<Track*>(::IceProxy::Ice::Object::ice_timeout(__timeout).get());
    }
    
    ::IceInternal::ProxyHandle<Track> ice_connectionId(const ::std::string& __id) const
    {
        return dynamic_cast<Track*>(::IceProxy::Ice::Object::ice_connectionId(__id).get());
    }
    
    ::IceInternal::ProxyHandle<Track> ice_encodingVersion(const ::Ice::EncodingVersion& __v) const
    {
        return dynamic_cast<Track*>(::IceProxy::Ice::Object::ice_encodingVersion(__v).get());
    }
    
    static const ::std::string& ice_staticId();

private: 

    virtual ::IceInternal::Handle< ::IceDelegateM::Ice::Object> __createDelegateM();
    virtual ::IceInternal::Handle< ::IceDelegateD::Ice::Object> __createDelegateD();
    virtual ::IceProxy::Ice::Object* __newInstance() const;
};

class Player : virtual public ::IceProxy::Ice::Object
{
public:

    void addTrack(const ::std::string& name, const ::std::string& album, const ::std::string& author, const ::std::string& singer, const ::std::string& path)
    {
        addTrack(name, album, author, singer, path, 0);
    }
    void addTrack(const ::std::string& name, const ::std::string& album, const ::std::string& author, const ::std::string& singer, const ::std::string& path, const ::Ice::Context& __ctx)
    {
        addTrack(name, album, author, singer, path, &__ctx);
    }
#ifdef ICE_CPP11
    ::Ice::AsyncResultPtr
    begin_addTrack(const ::std::string& name, const ::std::string& album, const ::std::string& author, const ::std::string& singer, const ::std::string& path, const ::IceInternal::Function<void ()>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& __sent = ::IceInternal::Function<void (bool)>())
    {
        return begin_addTrack(name, album, author, singer, path, 0, new ::IceInternal::Cpp11FnOnewayCallbackNC(__response, __exception, __sent));
    }
    ::Ice::AsyncResultPtr
    begin_addTrack(const ::std::string& name, const ::std::string& album, const ::std::string& author, const ::std::string& singer, const ::std::string& path, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_addTrack(name, album, author, singer, path, 0, ::Ice::newCallback(__completed, __sent), 0);
    }
    ::Ice::AsyncResultPtr
    begin_addTrack(const ::std::string& name, const ::std::string& album, const ::std::string& author, const ::std::string& singer, const ::std::string& path, const ::Ice::Context& __ctx, const ::IceInternal::Function<void ()>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& __sent = ::IceInternal::Function<void (bool)>())
    {
        return begin_addTrack(name, album, author, singer, path, &__ctx, new ::IceInternal::Cpp11FnOnewayCallbackNC(__response, __exception, __sent), 0);
    }
    ::Ice::AsyncResultPtr
    begin_addTrack(const ::std::string& name, const ::std::string& album, const ::std::string& author, const ::std::string& singer, const ::std::string& path, const ::Ice::Context& __ctx, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_addTrack(name, album, author, singer, path, &__ctx, ::Ice::newCallback(__completed, __sent));
    }
#endif

    ::Ice::AsyncResultPtr begin_addTrack(const ::std::string& name, const ::std::string& album, const ::std::string& author, const ::std::string& singer, const ::std::string& path)
    {
        return begin_addTrack(name, album, author, singer, path, 0, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_addTrack(const ::std::string& name, const ::std::string& album, const ::std::string& author, const ::std::string& singer, const ::std::string& path, const ::Ice::Context& __ctx)
    {
        return begin_addTrack(name, album, author, singer, path, &__ctx, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_addTrack(const ::std::string& name, const ::std::string& album, const ::std::string& author, const ::std::string& singer, const ::std::string& path, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_addTrack(name, album, author, singer, path, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_addTrack(const ::std::string& name, const ::std::string& album, const ::std::string& author, const ::std::string& singer, const ::std::string& path, const ::Ice::Context& __ctx, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_addTrack(name, album, author, singer, path, &__ctx, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_addTrack(const ::std::string& name, const ::std::string& album, const ::std::string& author, const ::std::string& singer, const ::std::string& path, const ::streaming::Callback_Player_addTrackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_addTrack(name, album, author, singer, path, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_addTrack(const ::std::string& name, const ::std::string& album, const ::std::string& author, const ::std::string& singer, const ::std::string& path, const ::Ice::Context& __ctx, const ::streaming::Callback_Player_addTrackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_addTrack(name, album, author, singer, path, &__ctx, __del, __cookie);
    }

    void end_addTrack(const ::Ice::AsyncResultPtr&);
    
private:

    void addTrack(const ::std::string&, const ::std::string&, const ::std::string&, const ::std::string&, const ::std::string&, const ::Ice::Context*);
    ::Ice::AsyncResultPtr begin_addTrack(const ::std::string&, const ::std::string&, const ::std::string&, const ::std::string&, const ::std::string&, const ::Ice::Context*, const ::IceInternal::CallbackBasePtr&, const ::Ice::LocalObjectPtr& __cookie = 0);
    
public:

    void deleteTrack(const ::std::string& name)
    {
        deleteTrack(name, 0);
    }
    void deleteTrack(const ::std::string& name, const ::Ice::Context& __ctx)
    {
        deleteTrack(name, &__ctx);
    }
#ifdef ICE_CPP11
    ::Ice::AsyncResultPtr
    begin_deleteTrack(const ::std::string& name, const ::IceInternal::Function<void ()>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& __sent = ::IceInternal::Function<void (bool)>())
    {
        return begin_deleteTrack(name, 0, new ::IceInternal::Cpp11FnOnewayCallbackNC(__response, __exception, __sent));
    }
    ::Ice::AsyncResultPtr
    begin_deleteTrack(const ::std::string& name, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_deleteTrack(name, 0, ::Ice::newCallback(__completed, __sent), 0);
    }
    ::Ice::AsyncResultPtr
    begin_deleteTrack(const ::std::string& name, const ::Ice::Context& __ctx, const ::IceInternal::Function<void ()>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& __sent = ::IceInternal::Function<void (bool)>())
    {
        return begin_deleteTrack(name, &__ctx, new ::IceInternal::Cpp11FnOnewayCallbackNC(__response, __exception, __sent), 0);
    }
    ::Ice::AsyncResultPtr
    begin_deleteTrack(const ::std::string& name, const ::Ice::Context& __ctx, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_deleteTrack(name, &__ctx, ::Ice::newCallback(__completed, __sent));
    }
#endif

    ::Ice::AsyncResultPtr begin_deleteTrack(const ::std::string& name)
    {
        return begin_deleteTrack(name, 0, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_deleteTrack(const ::std::string& name, const ::Ice::Context& __ctx)
    {
        return begin_deleteTrack(name, &__ctx, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_deleteTrack(const ::std::string& name, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_deleteTrack(name, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_deleteTrack(const ::std::string& name, const ::Ice::Context& __ctx, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_deleteTrack(name, &__ctx, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_deleteTrack(const ::std::string& name, const ::streaming::Callback_Player_deleteTrackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_deleteTrack(name, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_deleteTrack(const ::std::string& name, const ::Ice::Context& __ctx, const ::streaming::Callback_Player_deleteTrackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_deleteTrack(name, &__ctx, __del, __cookie);
    }

    void end_deleteTrack(const ::Ice::AsyncResultPtr&);
    
private:

    void deleteTrack(const ::std::string&, const ::Ice::Context*);
    ::Ice::AsyncResultPtr begin_deleteTrack(const ::std::string&, const ::Ice::Context*, const ::IceInternal::CallbackBasePtr&, const ::Ice::LocalObjectPtr& __cookie = 0);
    
public:

    ::streaming::TrackPtr searchTrack(const ::std::string& name)
    {
        return searchTrack(name, 0);
    }
    ::streaming::TrackPtr searchTrack(const ::std::string& name, const ::Ice::Context& __ctx)
    {
        return searchTrack(name, &__ctx);
    }
#ifdef ICE_CPP11
    ::Ice::AsyncResultPtr
    begin_searchTrack(const ::std::string& name, const ::IceInternal::Function<void (const ::streaming::TrackPtr&)>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& __sent = ::IceInternal::Function<void (bool)>())
    {
        return __begin_searchTrack(name, 0, __response, __exception, __sent);
    }
    ::Ice::AsyncResultPtr
    begin_searchTrack(const ::std::string& name, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_searchTrack(name, 0, ::Ice::newCallback(__completed, __sent), 0);
    }
    ::Ice::AsyncResultPtr
    begin_searchTrack(const ::std::string& name, const ::Ice::Context& __ctx, const ::IceInternal::Function<void (const ::streaming::TrackPtr&)>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& __sent = ::IceInternal::Function<void (bool)>())
    {
        return __begin_searchTrack(name, &__ctx, __response, __exception, __sent);
    }
    ::Ice::AsyncResultPtr
    begin_searchTrack(const ::std::string& name, const ::Ice::Context& __ctx, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_searchTrack(name, &__ctx, ::Ice::newCallback(__completed, __sent));
    }
    
private:

    ::Ice::AsyncResultPtr __begin_searchTrack(const ::std::string& name, const ::Ice::Context* __ctx, const ::IceInternal::Function<void (const ::streaming::TrackPtr&)>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception, const ::IceInternal::Function<void (bool)>& __sent)
    {
        class Cpp11CB : public ::IceInternal::Cpp11FnCallbackNC
        {
        public:

            Cpp11CB(const ::std::function<void (const ::streaming::TrackPtr&)>& responseFunc, const ::std::function<void (const ::Ice::Exception&)>& exceptionFunc, const ::std::function<void (bool)>& sentFunc) :
                ::IceInternal::Cpp11FnCallbackNC(exceptionFunc, sentFunc),
                _response(responseFunc)
            {
                CallbackBase::checkCallback(true, responseFunc || exceptionFunc != nullptr);
            }

            virtual void __completed(const ::Ice::AsyncResultPtr& __result) const
            {
                ::streaming::PlayerPrx __proxy = ::streaming::PlayerPrx::uncheckedCast(__result->getProxy());
                ::streaming::TrackPtr __ret;
                try
                {
                    __ret = __proxy->end_searchTrack(__result);
                }
                catch(::Ice::Exception& ex)
                {
                    Cpp11FnCallbackNC::__exception(__result, ex);
                    return;
                }
                if(_response != nullptr)
                {
                    _response(__ret);
                }
            }
        
        private:
            
            ::std::function<void (const ::streaming::TrackPtr&)> _response;
        };
        return begin_searchTrack(name, __ctx, new Cpp11CB(__response, __exception, __sent));
    }
    
public:
#endif

    ::Ice::AsyncResultPtr begin_searchTrack(const ::std::string& name)
    {
        return begin_searchTrack(name, 0, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_searchTrack(const ::std::string& name, const ::Ice::Context& __ctx)
    {
        return begin_searchTrack(name, &__ctx, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_searchTrack(const ::std::string& name, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_searchTrack(name, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_searchTrack(const ::std::string& name, const ::Ice::Context& __ctx, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_searchTrack(name, &__ctx, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_searchTrack(const ::std::string& name, const ::streaming::Callback_Player_searchTrackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_searchTrack(name, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_searchTrack(const ::std::string& name, const ::Ice::Context& __ctx, const ::streaming::Callback_Player_searchTrackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_searchTrack(name, &__ctx, __del, __cookie);
    }

    ::streaming::TrackPtr end_searchTrack(const ::Ice::AsyncResultPtr&);
    
private:

    ::streaming::TrackPtr searchTrack(const ::std::string&, const ::Ice::Context*);
    ::Ice::AsyncResultPtr begin_searchTrack(const ::std::string&, const ::Ice::Context*, const ::IceInternal::CallbackBasePtr&, const ::Ice::LocalObjectPtr& __cookie = 0);
    
public:

    void playTrack(const ::std::string& name)
    {
        playTrack(name, 0);
    }
    void playTrack(const ::std::string& name, const ::Ice::Context& __ctx)
    {
        playTrack(name, &__ctx);
    }
#ifdef ICE_CPP11
    ::Ice::AsyncResultPtr
    begin_playTrack(const ::std::string& name, const ::IceInternal::Function<void ()>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& __sent = ::IceInternal::Function<void (bool)>())
    {
        return begin_playTrack(name, 0, new ::IceInternal::Cpp11FnOnewayCallbackNC(__response, __exception, __sent));
    }
    ::Ice::AsyncResultPtr
    begin_playTrack(const ::std::string& name, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_playTrack(name, 0, ::Ice::newCallback(__completed, __sent), 0);
    }
    ::Ice::AsyncResultPtr
    begin_playTrack(const ::std::string& name, const ::Ice::Context& __ctx, const ::IceInternal::Function<void ()>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& __sent = ::IceInternal::Function<void (bool)>())
    {
        return begin_playTrack(name, &__ctx, new ::IceInternal::Cpp11FnOnewayCallbackNC(__response, __exception, __sent), 0);
    }
    ::Ice::AsyncResultPtr
    begin_playTrack(const ::std::string& name, const ::Ice::Context& __ctx, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_playTrack(name, &__ctx, ::Ice::newCallback(__completed, __sent));
    }
#endif

    ::Ice::AsyncResultPtr begin_playTrack(const ::std::string& name)
    {
        return begin_playTrack(name, 0, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_playTrack(const ::std::string& name, const ::Ice::Context& __ctx)
    {
        return begin_playTrack(name, &__ctx, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_playTrack(const ::std::string& name, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_playTrack(name, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_playTrack(const ::std::string& name, const ::Ice::Context& __ctx, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_playTrack(name, &__ctx, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_playTrack(const ::std::string& name, const ::streaming::Callback_Player_playTrackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_playTrack(name, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_playTrack(const ::std::string& name, const ::Ice::Context& __ctx, const ::streaming::Callback_Player_playTrackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_playTrack(name, &__ctx, __del, __cookie);
    }

    void end_playTrack(const ::Ice::AsyncResultPtr&);
    
private:

    void playTrack(const ::std::string&, const ::Ice::Context*);
    ::Ice::AsyncResultPtr begin_playTrack(const ::std::string&, const ::Ice::Context*, const ::IceInternal::CallbackBasePtr&, const ::Ice::LocalObjectPtr& __cookie = 0);
    
public:
    
    ::IceInternal::ProxyHandle<Player> ice_context(const ::Ice::Context& __context) const
    {
        return dynamic_cast<Player*>(::IceProxy::Ice::Object::ice_context(__context).get());
    }
    
    ::IceInternal::ProxyHandle<Player> ice_adapterId(const ::std::string& __id) const
    {
        return dynamic_cast<Player*>(::IceProxy::Ice::Object::ice_adapterId(__id).get());
    }
    
    ::IceInternal::ProxyHandle<Player> ice_endpoints(const ::Ice::EndpointSeq& __endpoints) const
    {
        return dynamic_cast<Player*>(::IceProxy::Ice::Object::ice_endpoints(__endpoints).get());
    }
    
    ::IceInternal::ProxyHandle<Player> ice_locatorCacheTimeout(int __timeout) const
    {
        return dynamic_cast<Player*>(::IceProxy::Ice::Object::ice_locatorCacheTimeout(__timeout).get());
    }
    
    ::IceInternal::ProxyHandle<Player> ice_connectionCached(bool __cached) const
    {
        return dynamic_cast<Player*>(::IceProxy::Ice::Object::ice_connectionCached(__cached).get());
    }
    
    ::IceInternal::ProxyHandle<Player> ice_endpointSelection(::Ice::EndpointSelectionType __est) const
    {
        return dynamic_cast<Player*>(::IceProxy::Ice::Object::ice_endpointSelection(__est).get());
    }
    
    ::IceInternal::ProxyHandle<Player> ice_secure(bool __secure) const
    {
        return dynamic_cast<Player*>(::IceProxy::Ice::Object::ice_secure(__secure).get());
    }
    
    ::IceInternal::ProxyHandle<Player> ice_preferSecure(bool __preferSecure) const
    {
        return dynamic_cast<Player*>(::IceProxy::Ice::Object::ice_preferSecure(__preferSecure).get());
    }
    
    ::IceInternal::ProxyHandle<Player> ice_router(const ::Ice::RouterPrx& __router) const
    {
        return dynamic_cast<Player*>(::IceProxy::Ice::Object::ice_router(__router).get());
    }
    
    ::IceInternal::ProxyHandle<Player> ice_locator(const ::Ice::LocatorPrx& __locator) const
    {
        return dynamic_cast<Player*>(::IceProxy::Ice::Object::ice_locator(__locator).get());
    }
    
    ::IceInternal::ProxyHandle<Player> ice_collocationOptimized(bool __co) const
    {
        return dynamic_cast<Player*>(::IceProxy::Ice::Object::ice_collocationOptimized(__co).get());
    }
    
    ::IceInternal::ProxyHandle<Player> ice_twoway() const
    {
        return dynamic_cast<Player*>(::IceProxy::Ice::Object::ice_twoway().get());
    }
    
    ::IceInternal::ProxyHandle<Player> ice_oneway() const
    {
        return dynamic_cast<Player*>(::IceProxy::Ice::Object::ice_oneway().get());
    }
    
    ::IceInternal::ProxyHandle<Player> ice_batchOneway() const
    {
        return dynamic_cast<Player*>(::IceProxy::Ice::Object::ice_batchOneway().get());
    }
    
    ::IceInternal::ProxyHandle<Player> ice_datagram() const
    {
        return dynamic_cast<Player*>(::IceProxy::Ice::Object::ice_datagram().get());
    }
    
    ::IceInternal::ProxyHandle<Player> ice_batchDatagram() const
    {
        return dynamic_cast<Player*>(::IceProxy::Ice::Object::ice_batchDatagram().get());
    }
    
    ::IceInternal::ProxyHandle<Player> ice_compress(bool __compress) const
    {
        return dynamic_cast<Player*>(::IceProxy::Ice::Object::ice_compress(__compress).get());
    }
    
    ::IceInternal::ProxyHandle<Player> ice_timeout(int __timeout) const
    {
        return dynamic_cast<Player*>(::IceProxy::Ice::Object::ice_timeout(__timeout).get());
    }
    
    ::IceInternal::ProxyHandle<Player> ice_connectionId(const ::std::string& __id) const
    {
        return dynamic_cast<Player*>(::IceProxy::Ice::Object::ice_connectionId(__id).get());
    }
    
    ::IceInternal::ProxyHandle<Player> ice_encodingVersion(const ::Ice::EncodingVersion& __v) const
    {
        return dynamic_cast<Player*>(::IceProxy::Ice::Object::ice_encodingVersion(__v).get());
    }
    
    static const ::std::string& ice_staticId();

private: 

    virtual ::IceInternal::Handle< ::IceDelegateM::Ice::Object> __createDelegateM();
    virtual ::IceInternal::Handle< ::IceDelegateD::Ice::Object> __createDelegateD();
    virtual ::IceProxy::Ice::Object* __newInstance() const;
};

}

}

namespace IceDelegate
{

namespace streaming
{

class Track : virtual public ::IceDelegate::Ice::Object
{
public:

    virtual void viewAllTract(const ::Ice::Context*, ::IceInternal::InvocationObserver&) = 0;
};

class Player : virtual public ::IceDelegate::Ice::Object
{
public:

    virtual void addTrack(const ::std::string&, const ::std::string&, const ::std::string&, const ::std::string&, const ::std::string&, const ::Ice::Context*, ::IceInternal::InvocationObserver&) = 0;

    virtual void deleteTrack(const ::std::string&, const ::Ice::Context*, ::IceInternal::InvocationObserver&) = 0;

    virtual ::streaming::TrackPtr searchTrack(const ::std::string&, const ::Ice::Context*, ::IceInternal::InvocationObserver&) = 0;

    virtual void playTrack(const ::std::string&, const ::Ice::Context*, ::IceInternal::InvocationObserver&) = 0;
};

}

}

namespace IceDelegateM
{

namespace streaming
{

class Track : virtual public ::IceDelegate::streaming::Track,
              virtual public ::IceDelegateM::Ice::Object
{
public:

    virtual void viewAllTract(const ::Ice::Context*, ::IceInternal::InvocationObserver&);
};

class Player : virtual public ::IceDelegate::streaming::Player,
               virtual public ::IceDelegateM::Ice::Object
{
public:

    virtual void addTrack(const ::std::string&, const ::std::string&, const ::std::string&, const ::std::string&, const ::std::string&, const ::Ice::Context*, ::IceInternal::InvocationObserver&);

    virtual void deleteTrack(const ::std::string&, const ::Ice::Context*, ::IceInternal::InvocationObserver&);

    virtual ::streaming::TrackPtr searchTrack(const ::std::string&, const ::Ice::Context*, ::IceInternal::InvocationObserver&);

    virtual void playTrack(const ::std::string&, const ::Ice::Context*, ::IceInternal::InvocationObserver&);
};

}

}

namespace IceDelegateD
{

namespace streaming
{

class Track : virtual public ::IceDelegate::streaming::Track,
              virtual public ::IceDelegateD::Ice::Object
{
public:

    virtual void viewAllTract(const ::Ice::Context*, ::IceInternal::InvocationObserver&);
};

class Player : virtual public ::IceDelegate::streaming::Player,
               virtual public ::IceDelegateD::Ice::Object
{
public:

    virtual void addTrack(const ::std::string&, const ::std::string&, const ::std::string&, const ::std::string&, const ::std::string&, const ::Ice::Context*, ::IceInternal::InvocationObserver&);

    virtual void deleteTrack(const ::std::string&, const ::Ice::Context*, ::IceInternal::InvocationObserver&);

    virtual ::streaming::TrackPtr searchTrack(const ::std::string&, const ::Ice::Context*, ::IceInternal::InvocationObserver&);

    virtual void playTrack(const ::std::string&, const ::Ice::Context*, ::IceInternal::InvocationObserver&);
};

}

}

namespace streaming
{

class Track : virtual public ::Ice::Object
{
public:

    typedef TrackPrx ProxyType;
    typedef TrackPtr PointerType;

    Track()
    {
    }

    Track(const ::std::string& __ice_name, const ::std::string& __ice_album, const ::std::string& __ice_author, const ::std::string& __ice_singer, const ::std::string& __ice_path) :
        name(__ice_name),
        album(__ice_album),
        author(__ice_author),
        singer(__ice_singer),
        path(__ice_path)
    {
    }

    virtual ::Ice::ObjectPtr ice_clone() const;

    virtual bool ice_isA(const ::std::string&, const ::Ice::Current& = ::Ice::Current()) const;
    virtual ::std::vector< ::std::string> ice_ids(const ::Ice::Current& = ::Ice::Current()) const;
    virtual const ::std::string& ice_id(const ::Ice::Current& = ::Ice::Current()) const;
    static const ::std::string& ice_staticId();


    virtual void viewAllTract(const ::Ice::Current& = ::Ice::Current()) = 0;
    ::Ice::DispatchStatus ___viewAllTract(::IceInternal::Incoming&, const ::Ice::Current&);

    virtual ::Ice::DispatchStatus __dispatch(::IceInternal::Incoming&, const ::Ice::Current&);

protected:
    virtual void __writeImpl(::IceInternal::BasicStream*) const;
    virtual void __readImpl(::IceInternal::BasicStream*);
    #ifdef __SUNPRO_CC
    using ::Ice::Object::__writeImpl;
    using ::Ice::Object::__readImpl;
    #endif

public:

    ::std::string name;

    ::std::string album;

    ::std::string author;

    ::std::string singer;

    ::std::string path;
};

inline bool operator==(const Track& l, const Track& r)
{
    return static_cast<const ::Ice::Object&>(l) == static_cast<const ::Ice::Object&>(r);
}

inline bool operator<(const Track& l, const Track& r)
{
    return static_cast<const ::Ice::Object&>(l) < static_cast<const ::Ice::Object&>(r);
}

class Player : virtual public ::Ice::Object
{
public:

    typedef PlayerPrx ProxyType;
    typedef PlayerPtr PointerType;

    virtual bool ice_isA(const ::std::string&, const ::Ice::Current& = ::Ice::Current()) const;
    virtual ::std::vector< ::std::string> ice_ids(const ::Ice::Current& = ::Ice::Current()) const;
    virtual const ::std::string& ice_id(const ::Ice::Current& = ::Ice::Current()) const;
    static const ::std::string& ice_staticId();

    virtual void addTrack(const ::std::string&, const ::std::string&, const ::std::string&, const ::std::string&, const ::std::string&, const ::Ice::Current& = ::Ice::Current()) = 0;
    ::Ice::DispatchStatus ___addTrack(::IceInternal::Incoming&, const ::Ice::Current&);

    virtual void deleteTrack(const ::std::string&, const ::Ice::Current& = ::Ice::Current()) = 0;
    ::Ice::DispatchStatus ___deleteTrack(::IceInternal::Incoming&, const ::Ice::Current&);

    virtual ::streaming::TrackPtr searchTrack(const ::std::string&, const ::Ice::Current& = ::Ice::Current()) = 0;
    ::Ice::DispatchStatus ___searchTrack(::IceInternal::Incoming&, const ::Ice::Current&);

    virtual void playTrack(const ::std::string&, const ::Ice::Current& = ::Ice::Current()) = 0;
    ::Ice::DispatchStatus ___playTrack(::IceInternal::Incoming&, const ::Ice::Current&);

    virtual ::Ice::DispatchStatus __dispatch(::IceInternal::Incoming&, const ::Ice::Current&);

protected:
    virtual void __writeImpl(::IceInternal::BasicStream*) const;
    virtual void __readImpl(::IceInternal::BasicStream*);
    #ifdef __SUNPRO_CC
    using ::Ice::Object::__writeImpl;
    using ::Ice::Object::__readImpl;
    #endif
};

inline bool operator==(const Player& l, const Player& r)
{
    return static_cast<const ::Ice::Object&>(l) == static_cast<const ::Ice::Object&>(r);
}

inline bool operator<(const Player& l, const Player& r)
{
    return static_cast<const ::Ice::Object&>(l) < static_cast<const ::Ice::Object&>(r);
}

}

namespace streaming
{

template<class T>
class CallbackNC_Track_viewAllTract : public Callback_Track_viewAllTract_Base, public ::IceInternal::OnewayCallbackNC<T>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception&);
    typedef void (T::*Sent)(bool);
    typedef void (T::*Response)();

    CallbackNC_Track_viewAllTract(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::OnewayCallbackNC<T>(obj, cb, excb, sentcb)
    {
    }
};

template<class T> Callback_Track_viewAllTractPtr
newCallback_Track_viewAllTract(const IceUtil::Handle<T>& instance, void (T::*cb)(), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_Track_viewAllTract<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_Track_viewAllTractPtr
newCallback_Track_viewAllTract(const IceUtil::Handle<T>& instance, void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_Track_viewAllTract<T>(instance, 0, excb, sentcb);
}

template<class T> Callback_Track_viewAllTractPtr
newCallback_Track_viewAllTract(T* instance, void (T::*cb)(), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_Track_viewAllTract<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_Track_viewAllTractPtr
newCallback_Track_viewAllTract(T* instance, void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_Track_viewAllTract<T>(instance, 0, excb, sentcb);
}

template<class T, typename CT>
class Callback_Track_viewAllTract : public Callback_Track_viewAllTract_Base, public ::IceInternal::OnewayCallback<T, CT>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception& , const CT&);
    typedef void (T::*Sent)(bool , const CT&);
    typedef void (T::*Response)(const CT&);

    Callback_Track_viewAllTract(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::OnewayCallback<T, CT>(obj, cb, excb, sentcb)
    {
    }
};

template<class T, typename CT> Callback_Track_viewAllTractPtr
newCallback_Track_viewAllTract(const IceUtil::Handle<T>& instance, void (T::*cb)(const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_Track_viewAllTract<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_Track_viewAllTractPtr
newCallback_Track_viewAllTract(const IceUtil::Handle<T>& instance, void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_Track_viewAllTract<T, CT>(instance, 0, excb, sentcb);
}

template<class T, typename CT> Callback_Track_viewAllTractPtr
newCallback_Track_viewAllTract(T* instance, void (T::*cb)(const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_Track_viewAllTract<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_Track_viewAllTractPtr
newCallback_Track_viewAllTract(T* instance, void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_Track_viewAllTract<T, CT>(instance, 0, excb, sentcb);
}

template<class T>
class CallbackNC_Player_addTrack : public Callback_Player_addTrack_Base, public ::IceInternal::OnewayCallbackNC<T>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception&);
    typedef void (T::*Sent)(bool);
    typedef void (T::*Response)();

    CallbackNC_Player_addTrack(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::OnewayCallbackNC<T>(obj, cb, excb, sentcb)
    {
    }
};

template<class T> Callback_Player_addTrackPtr
newCallback_Player_addTrack(const IceUtil::Handle<T>& instance, void (T::*cb)(), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_Player_addTrack<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_Player_addTrackPtr
newCallback_Player_addTrack(const IceUtil::Handle<T>& instance, void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_Player_addTrack<T>(instance, 0, excb, sentcb);
}

template<class T> Callback_Player_addTrackPtr
newCallback_Player_addTrack(T* instance, void (T::*cb)(), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_Player_addTrack<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_Player_addTrackPtr
newCallback_Player_addTrack(T* instance, void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_Player_addTrack<T>(instance, 0, excb, sentcb);
}

template<class T, typename CT>
class Callback_Player_addTrack : public Callback_Player_addTrack_Base, public ::IceInternal::OnewayCallback<T, CT>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception& , const CT&);
    typedef void (T::*Sent)(bool , const CT&);
    typedef void (T::*Response)(const CT&);

    Callback_Player_addTrack(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::OnewayCallback<T, CT>(obj, cb, excb, sentcb)
    {
    }
};

template<class T, typename CT> Callback_Player_addTrackPtr
newCallback_Player_addTrack(const IceUtil::Handle<T>& instance, void (T::*cb)(const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_Player_addTrack<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_Player_addTrackPtr
newCallback_Player_addTrack(const IceUtil::Handle<T>& instance, void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_Player_addTrack<T, CT>(instance, 0, excb, sentcb);
}

template<class T, typename CT> Callback_Player_addTrackPtr
newCallback_Player_addTrack(T* instance, void (T::*cb)(const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_Player_addTrack<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_Player_addTrackPtr
newCallback_Player_addTrack(T* instance, void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_Player_addTrack<T, CT>(instance, 0, excb, sentcb);
}

template<class T>
class CallbackNC_Player_deleteTrack : public Callback_Player_deleteTrack_Base, public ::IceInternal::OnewayCallbackNC<T>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception&);
    typedef void (T::*Sent)(bool);
    typedef void (T::*Response)();

    CallbackNC_Player_deleteTrack(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::OnewayCallbackNC<T>(obj, cb, excb, sentcb)
    {
    }
};

template<class T> Callback_Player_deleteTrackPtr
newCallback_Player_deleteTrack(const IceUtil::Handle<T>& instance, void (T::*cb)(), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_Player_deleteTrack<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_Player_deleteTrackPtr
newCallback_Player_deleteTrack(const IceUtil::Handle<T>& instance, void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_Player_deleteTrack<T>(instance, 0, excb, sentcb);
}

template<class T> Callback_Player_deleteTrackPtr
newCallback_Player_deleteTrack(T* instance, void (T::*cb)(), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_Player_deleteTrack<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_Player_deleteTrackPtr
newCallback_Player_deleteTrack(T* instance, void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_Player_deleteTrack<T>(instance, 0, excb, sentcb);
}

template<class T, typename CT>
class Callback_Player_deleteTrack : public Callback_Player_deleteTrack_Base, public ::IceInternal::OnewayCallback<T, CT>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception& , const CT&);
    typedef void (T::*Sent)(bool , const CT&);
    typedef void (T::*Response)(const CT&);

    Callback_Player_deleteTrack(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::OnewayCallback<T, CT>(obj, cb, excb, sentcb)
    {
    }
};

template<class T, typename CT> Callback_Player_deleteTrackPtr
newCallback_Player_deleteTrack(const IceUtil::Handle<T>& instance, void (T::*cb)(const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_Player_deleteTrack<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_Player_deleteTrackPtr
newCallback_Player_deleteTrack(const IceUtil::Handle<T>& instance, void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_Player_deleteTrack<T, CT>(instance, 0, excb, sentcb);
}

template<class T, typename CT> Callback_Player_deleteTrackPtr
newCallback_Player_deleteTrack(T* instance, void (T::*cb)(const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_Player_deleteTrack<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_Player_deleteTrackPtr
newCallback_Player_deleteTrack(T* instance, void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_Player_deleteTrack<T, CT>(instance, 0, excb, sentcb);
}

template<class T>
class CallbackNC_Player_searchTrack : public Callback_Player_searchTrack_Base, public ::IceInternal::TwowayCallbackNC<T>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception&);
    typedef void (T::*Sent)(bool);
    typedef void (T::*Response)(const ::streaming::TrackPtr&);

    CallbackNC_Player_searchTrack(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallbackNC<T>(obj, cb != 0, excb, sentcb), response(cb)
    {
    }

    virtual void __completed(const ::Ice::AsyncResultPtr& __result) const
    {
        ::streaming::PlayerPrx __proxy = ::streaming::PlayerPrx::uncheckedCast(__result->getProxy());
        ::streaming::TrackPtr __ret;
        try
        {
            __ret = __proxy->end_searchTrack(__result);
        }
        catch(::Ice::Exception& ex)
        {
            ::IceInternal::CallbackNC<T>::__exception(__result, ex);
            return;
        }
        if(response)
        {
            (::IceInternal::CallbackNC<T>::callback.get()->*response)(__ret);
        }
    }

    Response response;
};

template<class T> Callback_Player_searchTrackPtr
newCallback_Player_searchTrack(const IceUtil::Handle<T>& instance, void (T::*cb)(const ::streaming::TrackPtr&), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_Player_searchTrack<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_Player_searchTrackPtr
newCallback_Player_searchTrack(T* instance, void (T::*cb)(const ::streaming::TrackPtr&), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_Player_searchTrack<T>(instance, cb, excb, sentcb);
}

template<class T, typename CT>
class Callback_Player_searchTrack : public Callback_Player_searchTrack_Base, public ::IceInternal::TwowayCallback<T, CT>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception& , const CT&);
    typedef void (T::*Sent)(bool , const CT&);
    typedef void (T::*Response)(const ::streaming::TrackPtr&, const CT&);

    Callback_Player_searchTrack(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallback<T, CT>(obj, cb != 0, excb, sentcb), response(cb)
    {
    }

    virtual void __completed(const ::Ice::AsyncResultPtr& __result) const
    {
        ::streaming::PlayerPrx __proxy = ::streaming::PlayerPrx::uncheckedCast(__result->getProxy());
        ::streaming::TrackPtr __ret;
        try
        {
            __ret = __proxy->end_searchTrack(__result);
        }
        catch(::Ice::Exception& ex)
        {
            ::IceInternal::Callback<T, CT>::__exception(__result, ex);
            return;
        }
        if(response)
        {
            (::IceInternal::Callback<T, CT>::callback.get()->*response)(__ret, CT::dynamicCast(__result->getCookie()));
        }
    }

    Response response;
};

template<class T, typename CT> Callback_Player_searchTrackPtr
newCallback_Player_searchTrack(const IceUtil::Handle<T>& instance, void (T::*cb)(const ::streaming::TrackPtr&, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_Player_searchTrack<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_Player_searchTrackPtr
newCallback_Player_searchTrack(T* instance, void (T::*cb)(const ::streaming::TrackPtr&, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_Player_searchTrack<T, CT>(instance, cb, excb, sentcb);
}

template<class T>
class CallbackNC_Player_playTrack : public Callback_Player_playTrack_Base, public ::IceInternal::OnewayCallbackNC<T>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception&);
    typedef void (T::*Sent)(bool);
    typedef void (T::*Response)();

    CallbackNC_Player_playTrack(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::OnewayCallbackNC<T>(obj, cb, excb, sentcb)
    {
    }
};

template<class T> Callback_Player_playTrackPtr
newCallback_Player_playTrack(const IceUtil::Handle<T>& instance, void (T::*cb)(), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_Player_playTrack<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_Player_playTrackPtr
newCallback_Player_playTrack(const IceUtil::Handle<T>& instance, void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_Player_playTrack<T>(instance, 0, excb, sentcb);
}

template<class T> Callback_Player_playTrackPtr
newCallback_Player_playTrack(T* instance, void (T::*cb)(), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_Player_playTrack<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_Player_playTrackPtr
newCallback_Player_playTrack(T* instance, void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_Player_playTrack<T>(instance, 0, excb, sentcb);
}

template<class T, typename CT>
class Callback_Player_playTrack : public Callback_Player_playTrack_Base, public ::IceInternal::OnewayCallback<T, CT>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception& , const CT&);
    typedef void (T::*Sent)(bool , const CT&);
    typedef void (T::*Response)(const CT&);

    Callback_Player_playTrack(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::OnewayCallback<T, CT>(obj, cb, excb, sentcb)
    {
    }
};

template<class T, typename CT> Callback_Player_playTrackPtr
newCallback_Player_playTrack(const IceUtil::Handle<T>& instance, void (T::*cb)(const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_Player_playTrack<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_Player_playTrackPtr
newCallback_Player_playTrack(const IceUtil::Handle<T>& instance, void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_Player_playTrack<T, CT>(instance, 0, excb, sentcb);
}

template<class T, typename CT> Callback_Player_playTrackPtr
newCallback_Player_playTrack(T* instance, void (T::*cb)(const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_Player_playTrack<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_Player_playTrackPtr
newCallback_Player_playTrack(T* instance, void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_Player_playTrack<T, CT>(instance, 0, excb, sentcb);
}

}

#endif
